### ISSUE TITLE
Update S3 endpoint

### ISSUE THREAD

**Issue by mradamcox** [GeoDaCenter/air-quality-idw#2]
If this workflow is ever put back into use, we'll need to update the S3 bucket that the data is pushed to (this is handled via environment variable).

**Comment by Makosak** [comment]
Microsoft closed down the project, so no need... We should use the historical data we scraped to generate an aggregate metric though.

**Comment by mradamcox** [comment]
Ok, we'll handle that in a separate task. Closing this now, and will archive the repo (it can be unarchived later if we want to revive this code for a different endpoint or something).
